### ISSUE TITLE
Cannot find name 'Output'

### ISSUE THREAD

**Issue by algosig** [algosig/ReWrite#3]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\i82667\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.0.2
3 info using node@v7.9.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle rewrite@1.0.0~prestart: rewrite@1.0.0
6 silly lifecycle rewrite@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle rewrite@1.0.0~start: rewrite@1.0.0
8 verbose lifecycle rewrite@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle rewrite@1.0.0~start: PATH: C:\Users\i82667\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;E:\Docs\Projects\Angular2\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft Emulator Manager\1.0\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\PrivateAssemblies\;C:\Program Files\dotnet\;C:\Users\i82667\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\nodejs\;;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\i82667\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Users\i82667\AppData\Roaming\npm
10 verbose lifecycle rewrite@1.0.0~start: CWD: E:\Docs\Projects\Angular2
11 silly lifecycle rewrite@1.0.0~start: Args: [ '/d /s /c',
11 silly lifecycle   'tsc && concurrently "npm run tsc:w" "npm run server" ' ]
12 silly lifecycle rewrite@1.0.0~start: Returned: code: 2  signal: null
13 info lifecycle rewrite@1.0.0~start: Failed to exec start script
14 verbose stack Error: rewrite@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run server" `
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\i82667\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\i82667\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid rewrite@1.0.0
16 verbose cwd E:\Docs\Projects\Angular2
17 verbose Windows_NT 6.3.9600
18 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\i82667\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 verbose node v7.9.0
20 verbose npm  v5.0.2
21 error code ELIFECYCLE
22 error errno 2
23 error rewrite@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run server" `
23 error Exit status 2
24 error Failed at the rewrite@1.0.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 2, true ]

**Comment by algosig** [comment]
Issue Solved after Importing Output on a separate line.

https://github.com/algosig/ReWrite/commit/2ddd44411ccedaf1ec2540661c214f3bcbdf4bf2
